"""
Domain Pydantic Schemas for InkFlow-AI.

Responsibilities:
- Define structured LLM outputs and data models.
- Validate data invariants across workflow stages.
- Support flexible section word budgets (50–5000 words) and article length contracts.
"""

from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, Field, model_validator


class Task(BaseModel):
    """Writing task for a single blog section."""

    id: int = Field(description="Sequential section identifier starting at 1.")
    title: str = Field(description="Section heading title.")
    goal: str = Field(description="Core objective of this section.")
    bullets: list[str] = Field(default_factory=list, description="Key bullet points to cover.")
    target_words: int = Field(
        default=500,
        ge=50,
        le=5000,
        description="Target word count for this section (50–5000).",
    )
    technical_depth: str = Field(
        default="deep_dive",
        description="Technical depth of the section (e.g., deep_dive, implementation, conceptual, overview).",
    )
    requires_research: bool = Field(
        default=False,
        description="Whether this section requires external research evidence.",
    )
    requires_citations: bool = Field(
        default=False,
        description="Whether this section requires source citations.",
    )
    requires_code: bool = Field(
        default=False,
        description="Whether this section requires code snippets or examples.",
    )
    is_closing_section: bool = Field(
        default=False,
        description="Whether this is the dedicated final closing section.",
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_target_words(cls, data: dict) -> dict:
        """Allow aliases for target_words such as estimated_word_count or word_count."""
        if isinstance(data, dict):
            if "target_words" not in data:
                for alias in ("estimated_word_count", "target_word_count", "word_count"):
                    if alias in data and data[alias] is not None:
                        try:
                            data["target_words"] = int(data[alias])
                            break
                        except (ValueError, TypeError):
                            pass
        return data


class Plan(BaseModel):
    """Complete article execution plan generated by the Planner."""

    blog_title: str = Field(description="Overall click-worthy SEO title (55-65 characters).")
    subtitle: str = Field(
        default="",
        description="Single rich, comprehensive subtitle paragraph (140 to 220 characters / 20 to 35 words) explaining the core takeaway in simple words.",
    )

    audience: str = Field(default="Engineers and Technical Architects", description="Target reader persona.")
    tone: str = Field(default="Technical, analytical, and authoritative", description="Writing style and tone.")
    blog_kind: str = Field(default="guide", description="Category of article, e.g. tutorial, comparison, architecture.")

    target_word_count: int = Field(default=3500, description="Target total word count for the complete article.")
    min_word_count: int = Field(default=2500, description="Minimum acceptable total word count.")
    max_word_count: int = Field(default=5000, description="Maximum acceptable total word count.")

    closing_section_title: str = Field(default="", description="Planner-selected context-aware closing section heading.")
    article_thesis: str = Field(default="", description="Core engineering thesis of the article.")
    reader_outcome: str = Field(default="", description="What an engineer should understand differently after reading.")

    tasks: list[Task] = Field(default_factory=list, description="Ordered list of section writing tasks.")
    constraints: list[str] = Field(default_factory=list, description="Quality and domain constraints for the article.")


class EvidenceItem(BaseModel):
    """Single web research evidence item."""

    title: str = Field(description="Web page or document title.")
    url: str = Field(description="Source web URL.")
    snippet: str | None = Field(default="", description="Relevant content snippet.")
    source: str = Field(default="tavily", description="Research source engine.")


class EvidencePack(BaseModel):
    """Collection of research evidence items."""

    evidence: list[EvidenceItem] = Field(default_factory=list, description="Deduplicated research items.")


class RouterDecision(BaseModel):
    """Routing decision output from the Router node."""

    mode: Literal["closed_book", "hybrid", "open_book"] = Field(
        description="Routing execution mode based on topic requirements."
    )
    needs_research: bool = Field(
        default=False,
        description="Whether external web research is required.",
    )
    queries: list[str] = Field(
        default_factory=list,
        description="Search queries if research is needed.",
    )

    @model_validator(mode="before")
    @classmethod
    def infer_needs_research(cls, data: dict) -> dict:
        """Automatically compute needs_research if omitted by LLM output."""
        if isinstance(data, dict):
            if "needs_research" not in data:
                mode = data.get("mode", "closed_book")
                data["needs_research"] = mode != "closed_book"
        return data


class ImageSpec(BaseModel):
    """Specification for a technical image/diagram to generate."""

    placeholder: str = Field(description="Markdown placeholder string, e.g., [[IMAGE_1]].")
    filename: str = Field(description="Target PNG filename, e.g., architecture_diagram.png.")
    alt: str = Field(description="Short accessibility alt text.")
    caption: str = Field(description="Figure caption title.")
    prompt: str = Field(description="Detailed image generation prompt.")
    size: str = Field(default="2560x1440", description="Image dimensions.")
    quality: str = Field(default="medium", description="Image quality.")


class GlobalImagePlan(BaseModel):
    """Collection of planned technical illustrations for an article."""

    markdown_with_placeholders: str = Field(default="", description="Markdown with embedded placeholders.")
    images: list[ImageSpec] = Field(default_factory=list, description="List of image specifications to generate.")


class GeneratedImage(BaseModel):
    """Metadata for a generated and saved image file."""

    filename: str = Field(description="Saved PNG filename.")
    path: str = Field(description="Local file system path.")
    alt: str = Field(description="Alt text.")
    caption: str = Field(description="Caption text.")


class PublicationQAResult(BaseModel):
    """Result of deterministic publication QA verification."""

    status: Literal["PASS", "FAIL"] = Field(description="Publication QA outcome.")
    failures: list[str] = Field(default_factory=list, description="List of blocking hard failures.")
    warnings: list[str] = Field(default_factory=list, description="List of non-blocking warnings.")
    actual_word_count: int = Field(default=0, description="Total readable word count of final article.")
    target_word_count: int = Field(default=0, description="Requested target word count.")
    min_word_count: int = Field(default=0, description="Minimum acceptable word count.")
    max_word_count: int = Field(default=0, description="Maximum acceptable word count.")
    section_results: list[dict] = Field(default_factory=list, description="Per-section word count and status checks.")
    image_count: int = Field(default=0, description="Total number of valid images.")
    image_results: list[dict] = Field(default_factory=list, description="Image validation checks.")
    closing_section: str = Field(default="", description="Detected closing section title.")
    markdown_errors: list[str] = Field(default_factory=list, description="Structural Markdown syntax errors.")
