"""
Domain Pydantic Schemas for InkFlow-AI.

Responsibilities:
- Define structured LLM outputs and data models.
- Validate data invariants across workflow stages.
"""

from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, Field, model_validator


class Task(BaseModel):
    """Writing task for a single blog section."""

    id: int = Field(description="Sequential section identifier starting at 1.")
    title: str = Field(description="Section heading title.")
    goal: str = Field(description="Core objective of this section.")
    bullets: list[str] = Field(default_factory=list, description="Key bullet points to cover.")


class Plan(BaseModel):
    """Complete article execution plan generated by the Planner."""

    blog_title: str = Field(description="Overall blog title.")
    audience: str = Field(description="Target reader persona.")
    tone: str = Field(description="Writing style and tone.")
    blog_kind: str = Field(description="Category of article, e.g. tutorial, comparison.")
    tasks: list[Task] = Field(default_factory=list, description="Ordered list of section writing tasks.")


class EvidenceItem(BaseModel):
    """Single web research evidence item."""

    title: str = Field(description="Web page or document title.")
    url: str = Field(description="Source web URL.")
    snippet: str | None = Field(default="", description="Relevant content snippet.")
    source: str = Field(default="tavily", description="Research source engine.")


class EvidencePack(BaseModel):
    """Collection of research evidence items."""

    evidence: list[EvidenceItem] = Field(default_factory=list, description="Deduplicated research items.")


class RouterDecision(BaseModel):
    """Routing decision output from the Router node."""

    mode: Literal["closed_book", "hybrid", "open_book"] = Field(
        description="Routing execution mode based on topic requirements."
    )
    needs_research: bool = Field(
        default=False,
        description="Whether external web research is required.",
    )
    queries: list[str] = Field(
        default_factory=list,
        description="Search queries if research is needed.",
    )

    @model_validator(mode="before")
    @classmethod
    def infer_needs_research(cls, data: dict) -> dict:
        """Automatically compute needs_research if omitted by LLM output."""
        if isinstance(data, dict):
            if "needs_research" not in data:
                mode = data.get("mode", "closed_book")
                data["needs_research"] = mode != "closed_book"
        return data


class ImageSpec(BaseModel):
    """Specification for a technical image/diagram to generate."""

    placeholder: str = Field(description="Markdown placeholder string, e.g., [[IMAGE_1]].")
    filename: str = Field(description="Target PNG filename, e.g., architecture_diagram.png.")
    alt: str = Field(description="Short accessibility alt text.")
    caption: str = Field(description="Figure caption title.")
    prompt: str = Field(description="Detailed image generation prompt.")
    size: str = Field(default="1792x1024", description="Image dimensions.")
    quality: str = Field(default="medium", description="Image quality.")


class GlobalImagePlan(BaseModel):
    """Collection of planned technical illustrations for an article."""

    markdown_with_placeholders: str = Field(default="", description="Markdown with embedded placeholders.")
    images: list[ImageSpec] = Field(default_factory=list, description="List of image specifications to generate.")


class GeneratedImage(BaseModel):
    """Metadata for a generated and saved image file."""

    filename: str = Field(description="Saved PNG filename.")
    path: str = Field(description="Local file system path.")
    alt: str = Field(description="Alt text.")
    caption: str = Field(description="Caption text.")
