"""
Markdown builder for InkFlow-AI.

Responsibilities
----------------
- Assemble final Medium-grade Markdown document.
- Insert technical images inline directly at their respective sections.
- Format headings, code blocks, and captions.

Contains NO LLM logic.
"""

from __future__ import annotations

import re
from src.schemas.models import GeneratedImage, Plan


class MarkdownBuilder:
    """Build the final blog markdown with inline section images."""

    def build(
        self,
        plan: Plan,
        sections: list[str],
        images: list[GeneratedImage],
        markdown_with_placeholders: str = "",
    ) -> str:
        """
        Build the final markdown document with inline section images.

        Parameters
        ----------
        plan
            Article Plan outline containing blog_title.
        sections
            Generated markdown sections.
        images
            Generated images metadata.
        markdown_with_placeholders
            Full markdown containing [[IMAGE_1]], [[IMAGE_2]] placeholders.

        Returns
        -------
        str
        """
        # --------------------------------------------------
        # Determine base text from sections or placeholder markdown
        # --------------------------------------------------

        full_article = "\n\n".join(sections) if sections else ""

        # Always preserve the full, complete article markdown generated by writers & editor.
        if full_article.strip():
            base_text = full_article
        elif markdown_with_placeholders:
            base_text = markdown_with_placeholders
        else:
            base_text = ""


        if not base_text and plan and plan.blog_title:
            base_text = f"# {plan.blog_title}\n\n"

        # Normalize H1 title & subtitle block
        lines = base_text.split("\n")
        if plan and plan.blog_title:
            title_line = f"# {plan.blog_title}"
        elif lines and lines[0].startswith("#"):
            title_line = lines[0]
        else:
            title_line = "# Blog Title"

        # Extract existing subtitle if present
        content_start_idx = 0
        subtitle_line = ""
        
        for idx, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith("# ") and not title_line:
                title_line = stripped
                continue
            if stripped.startswith("*") and stripped.endswith("*") and len(stripped) > 2:
                if not subtitle_line:
                    subtitle_line = stripped
                content_start_idx = idx + 1
            elif stripped:
                if not subtitle_line and plan and plan.subtitle:
                    subtitle_line = f"*{plan.subtitle.strip()}*"
                if idx > content_start_idx and not subtitle_line:
                    content_start_idx = idx
                break

        if not subtitle_line and plan and plan.subtitle:
            subtitle_line = f"*{plan.subtitle.strip()}*"

        # Filter out any lingering duplicate title/subtitle lines from content
        body_lines = []
        in_body_code_block = False
        for line in lines[content_start_idx:]:
            s = line.strip()
            if s.startswith("```"):
                in_body_code_block = not in_body_code_block
                body_lines.append(line)
                continue

            if not in_body_code_block:
                if s.startswith("# ") and s.lower() == title_line.lower():
                    continue
                if s.startswith("# ") and s.lower() != title_line.lower():
                    # Convert rogue single-hash H1 section titles inside body to H2 section titles
                    body_lines.append(f"## {s[2:]}")
                    continue
                if s.startswith("*") and s.endswith("*") and s.lower() == subtitle_line.lower():
                    continue
                # Convert italicized subtitle lines directly beneath H2 headings into normal body text
                if s.startswith("*") and s.endswith("*") and len(body_lines) > 0 and body_lines[-1].startswith("## "):
                    body_lines.append(s[1:-1].strip())
                    continue

            body_lines.append(line)

        clean_body = "\n".join(body_lines).strip()
        base_text = f"{title_line}\n\n{subtitle_line}\n\n{clean_body}"

        # --------------------------------------------------
        # Method 1: Replace [[IMAGE_X]] placeholders inline
        # --------------------------------------------------
        has_placeholders = bool(re.search(r"\[\[?IMAGE_\d+\]?\]", base_text, re.IGNORECASE))

        if has_placeholders:
            final_md = base_text
            for idx, img in enumerate(images, 1):
                placeholder_patterns = [f"[[IMAGE_{idx}]]", f"[IMAGE_{idx}]"]
                image_url = f"images/{img.filename}"
                inline_md = f"\n\n![{img.alt}]({image_url})\n*{img.caption}*\n\n"

                for pat in placeholder_patterns:
                    if pat in final_md:
                        final_md = final_md.replace(pat, inline_md, 1)
                        break

            # Strip any remaining unreplaced image placeholders cleanly
            final_md = re.sub(r"\n*\[\[?IMAGE_\d+\]?\]\n*", "\n\n", final_md)
            return self._normalize_figure_numbers(final_md.strip())

        # --------------------------------------------------
        # Method 2: Semantic & Even Section Placement across H2/H3 Sections
        # --------------------------------------------------
        if not images:
            return self._normalize_figure_numbers(base_text.strip())

        # Split base_text into header/intro block and H2 sections
        sections_blocks = re.split(r"\n(?=## )", base_text)
        output_blocks = []

        stop_words = {'with', 'from', 'that', 'this', 'have', 'your', 'using', 'over', 'into', 'than', 'then', 'they', 'them', 'their', 'which', 'where', 'when', 'what', 'how', 'show', 'showing', 'diagram', 'visual', 'figure', 'image', 'architecture', 'system', 'flowchart', 'comparison', 'step', 'versus'}

        def get_kw(text: str) -> set[str]:
            words = re.findall(r'\b[a-zA-Z]{3,}\b', text.lower())
            return {w for w in words if w not in stop_words}

        conclusion_titles = {
            "final thoughts", "key takeaways", "summary", "conclusion",
            "practical recommendations", "choosing the right approach",
            "best practices recap", "what you should remember", "closing thoughts"
        }

        # Pre-compute per-block keywords (headings + first 250 chars of body)
        block_keywords: dict[int, set[str]] = {}
        for block_idx, block in enumerate(sections_blocks):
            if not block.startswith("## "):
                continue
            first_line = block.split("\n", 1)[0].replace("##", "").strip().lower()
            if any(ct in first_line for ct in conclusion_titles):
                continue
            heading_titles = re.findall(r"#{2,3}\s+([^\n]+)", block)
            body_snippet = re.sub(r"#{2,3}[^\n]+\n", "", block, count=3)[:250]
            bkw: set[str] = set()
            for h in heading_titles:
                bkw |= get_kw(h)
            bkw |= get_kw(body_snippet)
            block_keywords[block_idx] = bkw

        h2_indices = sorted(block_keywords.keys())


        # Score each image against each block, then assign best unique match
        # (greedy by highest score, one image per block)
        block_image_assignment: dict[int, list[GeneratedImage]] = {}
        used_blocks: set[int] = set()

        # Build scored (score, block_idx, img) triples and sort descending
        scored: list[tuple[int, int, GeneratedImage]] = []
        for img in images:
            img_kw = get_kw(img.caption or "") | get_kw(img.alt or "")
            for block_idx, bkw in block_keywords.items():
                overlap = len(img_kw & bkw)
                if overlap >= 1:
                    scored.append((overlap, block_idx, img))

        scored.sort(key=lambda t: t[0], reverse=True)

        assigned_images: set[int] = set()  # track by id()
        for score, block_idx, img in scored:
            if id(img) in assigned_images or block_idx in used_blocks:
                continue
            block_image_assignment[block_idx] = [img]
            used_blocks.add(block_idx)
            assigned_images.add(id(img))

        # Even-distribution fallback for images with no semantic match
        unassigned_images = [img for img in images if id(img) not in assigned_images]
        if unassigned_images and h2_indices:
            # Prefer mid-body sections; skip the first H2 if more than 2 remain
            free_indices = [i for i in h2_indices if i not in used_blocks]
            spread_indices = free_indices if free_indices else (
                h2_indices[1:] if len(h2_indices) > 2 else h2_indices
            )
            step = max(1, len(spread_indices) / max(len(unassigned_images), 1))
            for i, img in enumerate(unassigned_images):
                target = spread_indices[min(int(round(i * step)), len(spread_indices) - 1)]
                block_image_assignment.setdefault(target, []).append(img)

        # Build output blocks by placing assigned images into their corresponding section blocks
        for block_idx, block in enumerate(sections_blocks):
            if block_idx not in block_image_assignment:
                output_blocks.append(block)
                continue

            block_images = block_image_assignment[block_idx]
            block_lines = block.split("\n")
            in_code_block = False
            new_lines = []
            img_ptr = 0

            paragraph_count = 0
            for line in block_lines:
                stripped = line.strip()

                if stripped.startswith("```"):
                    in_code_block = not in_code_block
                    new_lines.append(line)
                    continue

                new_lines.append(line)

                if in_code_block:
                    continue

                # Reset paragraph count if we hit an H3 sub-heading
                if stripped.startswith("### "):
                    paragraph_count = 0
                    continue

                if (
                    stripped
                    and not stripped.startswith("#")
                    and not stripped.startswith(">")
                    and not stripped.startswith("- ")
                    and not stripped.startswith("* ")
                ):
                    paragraph_count += 1

                # Insert image after the 2nd paragraph inside the section for better flow
                if img_ptr < len(block_images) and paragraph_count >= 2:
                    img = block_images[img_ptr]
                    image_url = f"images/{img.filename}"
                    image_block = f"\n\n![{img.alt}]({image_url})\n*{img.caption}*\n"
                    new_lines.append(image_block)
                    img_ptr += 1
                    paragraph_count = 0

            # Append any remaining images not placed within paragraph flow
            new_lines.extend(
                f"\n\n![{img.alt}](images/{img.filename})\n*{img.caption}*\n"
                for img in block_images[img_ptr:]
            )

            output_blocks.append("\n".join(new_lines))

        raw_assembled = "\n\n".join(output_blocks).strip()
        return self._normalize_figure_numbers(raw_assembled)

    @staticmethod
    def _normalize_figure_numbers(markdown_text: str) -> str:
        """
        Renumber all Figure captions sequentially (Figure 1, Figure 2, Figure 3...)
        in the exact order they appear from top to bottom in the document.
        """
        fig_counter = 1

        def renumber_match(m: re.Match) -> str:
            nonlocal fig_counter
            prefix = m.group(1)
            content = m.group(2)
            suffix = m.group(3)
            result = f"{prefix}Figure {fig_counter}:{content}{suffix}"
            fig_counter += 1
            return result

        return re.sub(
            r"(\*|\*\*)Figure\s+\d+:(.+?)(\*|\*\*)",
            renumber_match,
            markdown_text,
            flags=re.IGNORECASE,
        )


markdown_builder = MarkdownBuilder()

