"""
Web search tool for InkFlow-AI.

Responsibilities
----------------
- Execute web searches using Tavily.
- Return EvidencePack containing EvidenceItems.
- Remove duplicate URLs.

Contains NO LLM logic.
"""

from __future__ import annotations

import logging

from tavily import TavilyClient
from src.config import TAVILY_API_KEY
from src.schemas.blog import EvidenceItem, EvidencePack

logger = logging.getLogger(__name__)


class WebSearchTool:
    """Execute web searches using Tavily."""

    def __init__(self) -> None:
        self._client = TavilyClient(
            api_key=TAVILY_API_KEY,
        )

    def search(self, queries: list[str], max_results: int = 5) -> EvidencePack:
        """
        Execute multiple search queries.

        Parameters
        ----------
        queries:
            Search queries generated by the router.

        max_results:
            Maximum search results returned per query.

        Returns
        -------
        EvidencePack
        """

        logger.info("Searching %d query(ies)...", len(queries))

        items: list[EvidenceItem] = []
        seen_urls: set[str] = set()

        for query in queries:

            response = self._client.search(
                query=query,
                max_results=max_results,
            )

            for result in response.get("results", []):

                url = result.get("url")

                if not url or url in seen_urls:
                    continue

                seen_urls.add(url)

                items.append(
                    EvidenceItem(
                        title=result.get("title", ""),
                        url=url,
                        snippet=result.get("content", ""),
                        source="tavily",
                    )
                )

        logger.info("Retrieved %d unique evidence item(s).", len(items))

        return EvidencePack(evidence=items)


web_search = WebSearchTool()
